In [361]:
import pandas as pd
import numpy as np
from collections import Counter

In [362]:
data = pd.read_excel("slides.xlsx")
data.head()
data.columns[1]
data.info()
data1= data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ex      12 non-null     object
 1   Alt     12 non-null     object
 2   Bar     12 non-null     object
 3   Fri     12 non-null     object
 4   Hun     12 non-null     object
 5   Pat     12 non-null     object
 6   Price   12 non-null     object
 7   Rain    12 non-null     object
 8   Res     12 non-null     object
 9   Type    12 non-null     object
 10  Est     12 non-null     object
 11  Goal    12 non-null     int64
dtypes: int64(1), object(11)
memory usage: 1.2+ KB

In [363]:
y = data.Goal
y

0     1
1     0
2     1
3     1
4     0
5     1
6     0
7     1
8     0
9     0
10    0
11    1
Name: Goal, dtype: int64

Begin the tree with the root node with all the data set<br>
Find the best attribute in the dataset <br>
Divide the Sinto subset that contains possible values <br>
Create the decision tree node which contains possible values <br>
Recursively make new decision tree using the subset of new node in step 3<br>

In [364]:
x=data.drop(['Goal'], axis=1)
x

     ex  Alt  Bar  Fri  Hun   Pat Price Rain  Res     Type        Est
0    x1  Yes   No   No  Yes  Some   $$$   No  Yes   French   "0 - 10"
1    x2  Yes   No   No  Yes  Full     $   No   No     Thai  "30 - 60"
2    x3   No  Yes   No   No  Some     $   No   No   Burger   "0 - 10"
3    x4  Yes   No  Yes  Yes  Full     $  Yes   No     Thai  "10 - 30"
4    x5  Yes   No  Yes   No  Full   $$$   No  Yes   French     "> 60"
5    x6   No  Yes   No  Yes  Some    $$  Yes  Yes  Italian   "0 - 10"
6    x7   No  Yes   No   No  None     $  Yes   No   Burger   "0 - 10"
7    x8   No   No   No  Yes  Some    $$  Yes  Yes     Thai   "0 - 10"
8    x9   No  Yes  Yes   No  Full     $  Yes   No   Burger     "> 60"
9   x10  Yes  Yes  Yes  Yes  Full   $$$   No  Yes  Italian  "10 - 30"
10  x11   No   No   No   No  None     $   No   No     Thai   "0 - 10"
11  x12  Yes  Yes  Yes  Yes  Full     $   No   No   Burger  "30 - 60"

In [365]:
x=x.drop(['ex'],axis=1)
x

    Alt  Bar  Fri  Hun   Pat Price Rain  Res     Type        Est
0   Yes   No   No  Yes  Some   $$$   No  Yes   French   "0 - 10"
1   Yes   No   No  Yes  Full     $   No   No     Thai  "30 - 60"
2    No  Yes   No   No  Some     $   No   No   Burger   "0 - 10"
3   Yes   No  Yes  Yes  Full     $  Yes   No     Thai  "10 - 30"
4   Yes   No  Yes   No  Full   $$$   No  Yes   French     "> 60"
5    No  Yes   No  Yes  Some    $$  Yes  Yes  Italian   "0 - 10"
6    No  Yes   No   No  None     $  Yes   No   Burger   "0 - 10"
7    No   No   No  Yes  Some    $$  Yes  Yes     Thai   "0 - 10"
8    No  Yes  Yes   No  Full     $  Yes   No   Burger     "> 60"
9   Yes  Yes  Yes  Yes  Full   $$$   No  Yes  Italian  "10 - 30"
10   No   No   No   No  None     $   No   No     Thai   "0 - 10"
11  Yes  Yes  Yes  Yes  Full     $   No   No   Burger  "30 - 60"

In [366]:
dict = {'Yes': 1, 'No': 0, 'Some':1, 'None':0, 'Full':2, '$':0, '$$':1,'$$$':2,'"0 - 10"':0,'"10 - 30"':1, '"30 - 60"': 2, '"> 60"':3 ,'French':0,'Thai':1,'Italian':2,'Burger':3,1:1,0:0}

In [367]:
x_np = x.to_numpy()
x_np

array([['Yes', 'No', 'No', 'Yes', 'Some', '$$$', 'No', 'Yes', 'French',
        '"0 - 10"'],
       ['Yes', 'No', 'No', 'Yes', 'Full', '$', 'No', 'No', 'Thai',
        '"30 - 60"'],
       ['No', 'Yes', 'No', 'No', 'Some', '$', 'No', 'No', 'Burger',
        '"0 - 10"'],
       ['Yes', 'No', 'Yes', 'Yes', 'Full', '$', 'Yes', 'No', 'Thai',
        '"10 - 30"'],
       ['Yes', 'No', 'Yes', 'No', 'Full', '$$$', 'No', 'Yes', 'French',
        '"> 60"'],
       ['No', 'Yes', 'No', 'Yes', 'Some', '$$', 'Yes', 'Yes', 'Italian',
        '"0 - 10"'],
       ['No', 'Yes', 'No', 'No', 'None', '$', 'Yes', 'No', 'Burger',
        '"0 - 10"'],
       ['No', 'No', 'No', 'Yes', 'Some', '$$', 'Yes', 'Yes', 'Thai',
        '"0 - 10"'],
       ['No', 'Yes', 'Yes', 'No', 'Full', '$', 'Yes', 'No', 'Burger',
        '"> 60"'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Full', '$$$', 'No', 'Yes',
        'Italian', '"10 - 30"'],
       ['No', 'No', 'No', 'No', 'None', '$', 'No', 'No', 'Thai',
        '"0 - 10"'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Full', '$', 'No', 'No', 'Burger',
        '"30 - 60"']], dtype=object)

In [368]:
for i in range(len(x_np)):
    for j in range(len(x_np[i])):
        # print(dict[x_np[i][j]])
        x_np[i][j] = dict[x_np[i][j]]

In [369]:
x_np

array([[1, 0, 0, 1, 1, 2, 0, 1, 0, 0],
       [1, 0, 0, 1, 2, 0, 0, 0, 1, 2],
       [0, 1, 0, 0, 1, 0, 0, 0, 3, 0],
       [1, 0, 1, 1, 2, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 2, 2, 0, 1, 0, 3],
       [0, 1, 0, 1, 1, 1, 1, 1, 2, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 3, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 0, 2, 0, 1, 0, 3, 3],
       [1, 1, 1, 1, 2, 2, 0, 1, 2, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 1, 1, 1, 2, 0, 0, 0, 3, 2]], dtype=object)

In [370]:
data = data

In [371]:
df = pd.DataFrame(x_np, )

In [372]:

from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
# x_train, x_test, y_train, y_test = train_test_split(x_np, y, test_size=0.2, random_state=1)

In [373]:
# x_train

In [374]:
class Node:
    def __init__(self, feature=None, threshold=None, children = None, gain = None,*,value= None) -> None:
        self.feature = feature
        self.threshold = threshold#?
        self.children = children
        self.value=value
        self.gain = gain

    def is_leaf_node(self):
        return self.value is not None

In [375]:

class DecisionTree:
    def __init__(self, min_samples_split=0, max_depth=100, childSize = 4
    , n_features=None):
        self.min_samples_split=min_samples_split
        self.max_depth=max_depth
        self.n_features=n_features
        self.root=None
        self.childSize = childSize

    def fit(self, X, y):
        self.n_features = X.shape[1] if not self.n_features else min(X.shape[1],self.n_features)
        self.root = self._grow_tree(X, y)

    def _grow_tree(self, X, y, depth=0):
        n_samples, n_feats = X.shape
        n_labels = len(np.unique(y))

        # check the stopping criteria
        if (depth>=self.max_depth or n_labels==1 or n_samples < self.min_samples_split):
            leaf_value = self._most_common_label(y)
            return Node(value=leaf_value)

        feat_idxs = np.random.choice(n_feats, self.n_features, replace=False)

        best_feature, best_thresh, best_gain = self._best_split(X, y, feat_idxs)

        child_idxs = self._split(X[: ,best_feature], best_thresh)
        child_idxs = np.array(child_idxs)
        children =[]
        for i in range(len(child_idxs)):
            # print(f'child:{child_idxs}')
            if y[child_idxs[i]].size == 0:
                print("child_idx is empty")
            children.append(self._grow_tree( X[child_idxs[i],:],y[child_idxs[i]],depth+1))
        node = Node(best_feature, best_thresh, children, best_gain)
        
        return node

#land deliyd
    def _best_split(self, X, y, feat_idxs):
        # best_gain = -1
        np.random.seed()
        # print(f'best split y size {y.size}')
        split_idx = None
        split_threshold = []
        best_gains = -1
        all_gain = []
        for feat_idx in feat_idxs:
            threshold = []
            X_column = X[:,feat_idx]
            thresholds = np.unique(X_column)
            temp = np.unique(thresholds)
            temp.sort()
            length = temp.size
            everyPart = length /  self.childSize
            for i in range(self.childSize - 1):
                num = int((i+1)* everyPart)
                if temp[num] not in threshold:
                    threshold.append(temp[num])
            gain = self._information_gain(y, X_column, threshold)  
            if feat_idx == 3:
                print(X_column, gain)
            all_gain.append((gain,feat_idx,y,X_column))
            if gain > best_gains:
                best_gains = gain
                split_idx = feat_idx
                split_threshold = threshold 
        # if feat_idx == 3:
            # print('____________________')
            # print(all_gain)       
            # print('____________________')
        return split_idx, split_threshold, best_gains


#split_idx -> best feature  

    def _information_gain(self, y, X_column, threshold):
        parent_entropy = self._entropy(y)
        children = self._split(X_column, threshold)
        # chil = 0
        # for i in children:
        #     chil += len(i)
        for i in children:
            if len(i) == 0:
                return 0
        n = len(y)
        n_l = []
        e_l = []
        for i in children:
            n_l.append(len(i))

        for i in children:
            e_l.append(self._entropy(y[i]))

        child_entropy = 0
        for i in range(len(n_l)):
            child_entropy += (n_l[i]/n) * e_l[i]
        # calculate the IG
        information_gain = parent_entropy - child_entropy
        # if information_gain < 0:
        # print(f'-------------------entropy smaller than zero')
        # print(f'len{X_column.size}')
        # print(f'information gain-> parent: {parent_entropy} child: {child_entropy}')
        # print(f'parentlen: {len(y)} child')
        # print(f'e_l -> {e_l}')
        # print(f'n_l -> {n_l}')
        # print(f'-------------------end')

        return information_gain

    def _split(self, X_column, split_thresh):
        #left_idxs = np.argwhere(X_column <= split_thresh).flatten()
        #indx of which argument is smaller than split_thresh and flatten give you one list 
        #right_idxs = np.argwhere(X_column > split_thresh).flatten()
        answer = []
        # temp = X_column
        split_thresh.sort()
        # if len(np.argwhere(X_column > split_thresh[0]).flatten()) == 0: 
        if np.any(np.argwhere(X_column < split_thresh[0])): 
            answer.append(np.argwhere(X_column < split_thresh[0]).flatten())
        count = 1
        while count < len(split_thresh) :
            # print(f'-------------------------------------{np.argwhere(X_column >= split_thresh).flatten()}')
            temp = np.argwhere(X_column >= split_thresh[count - 1]).flatten()
            temp2 = np.argwhere(X_column < split_thresh[count]).flatten()
            val = [val for val in temp if val in temp2]
            if val != []:
                # print(val)
                answer.append(np.array(val))

            count+= 1
           
        if np.any(np.argwhere(X_column >= split_thresh[len(split_thresh) - 1])): 
            answer.append(np.argwhere(X_column >= split_thresh[len(split_thresh) - 1]).flatten())

        # print(f'answer: {answer}')
        # print(f'X_column: {X_column}')
        # print(f'split_thresh: {split_thresh}')
        return answer

    def _entropy(self, y):
        hist = np.bincount(y)
        ps = hist / len(y)
        return -np.sum([p * np.log2(p) for p in ps if p>0])


    def _most_common_label(self, y):
        counter = Counter(y)
        # print(f'most common{y}')
        value = counter.most_common(1)[0][0]
        return value

    def predict(self, X):
        return np.array([self._traverse_tree(x, self.root) for x in X])

    def _traverse_tree(self, x, node):
        if node.is_leaf_node():
            return node.value
        for thr,i in zip( node.threshold,range(len(node.children))):
            if x[node.feature] <= thr:
                return self._traverse_tree(x, node.children[i])#TODO SORT TRESHOLDS
        return self._traverse_tree(x, node.children[len(node.children) - 1])

In [376]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [377]:
data = datasets.load_breast_cancer()
x1,y1 = data.data, data.target
print(type(x1))

<class 'numpy.ndarray'>

In [378]:
# x = x.to_numpy()
y = y.to_numpy()

In [379]:
# x_train , x_test, y_train, y_test = tarin = train_test_split(
#     x, y , test_size = 0.2, random_state = 1234
# )
# print(type(X_train))

In [380]:
x_np = x.to_numpy()
x_test = x_np

In [381]:
# y_train

In [382]:
clf = DecisionTree()
clf.fit(x_np, y)
prediction = clf.predict(x_test)

[1 1 0 1 0 1 0 1 0 1 0 1] 0.19570962879973086
[1 1 0 0 1 1] 0.2516291673878229
[1 1] 0.0
[1 1] 0.0

/tmp/ipykernel_74643/1368511314.py:28: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  child_idxs = np.array(child_idxs)

In [383]:
def accuracy(y, y_pred):
    return np.sum(y == y_pred)/len(y)

In [384]:
prediction

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1])

In [385]:
y

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1])

In [386]:
acc = accuracy(y, prediction)
print(acc)

1.0

In [387]:
# dataArr = np.array(data)
def dfs(tree:Node, depth = 0):
    if tree != None:
        if tree.children != None:
            print(depth * '\t' + f'threshold:{tree.threshold} and feature:{data1.columns[tree.feature + 1]} and gain: {tree.gain}')
            for child in tree.children:
                # print(depth * '\t' + f'value: {child.value} {child.threshold} and {child.feature}')
                dfs(child, depth+1)
        else:
            print(depth * '\t' + f'value: {tree.value}')

        
            
    # print(tree.root)
dfs(clf.root)

threshold:[0, 1, 2] and feature:Pat and gain: 0.5408520829727552
	value: 0
	value: 1
	threshold:[1, 2, 3] and feature:Est and gain: 0.2516291673878229
		threshold:[0, 1] and feature:Res and gain: 1.0
			value: 1
			value: 0
		threshold:[0, 1] and feature:Fri and gain: 1.0
			value: 0
			value: 1
		value: 0